from __future__ import annotations

import os
import sqlite3
from contextlib import asynccontextmanager
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field


BASE_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BASE_DIR / "data"
DB_PATH = Path(os.environ.get("YH_DB_PATH", str(DATA_DIR / "yhthestudio.db")))

# bcrypt hash generated by bcryptjs (cost=10) for password "admin123"
DEFAULT_ADMIN_BCRYPT_HASH = (
    "$2b$10$L44E.0mupOj9DbN5rZnIJuhF7v9K1zjP6xglMiaNoEsFYoHJ/HPH."
)


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def generate_placeholder_svg(text: str, width: int = 400, height: int = 300) -> str:
    # Keep this consistent with the original Node placeholder output (URI-encoded SVG).
    import urllib.parse

    safe_id = "".join(text.split())
    svg = f"""<svg width="{width}" height="{height}" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <linearGradient id="grad{safe_id}" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" style="stop-color:#1a1f3a;stop-opacity:1" />
        <stop offset="100%" style="stop-color:#0a0e27;stop-opacity:1" />
      </linearGradient>
    </defs>
    <rect width="100%" height="100%" fill="url(#grad{safe_id})"/>
    <circle cx="{width/2}" cy="{height/2 - 30}" r="40" fill="none" stroke="#00d4ff" stroke-width="2" opacity="0.5"/>
    <text x="50%" y="60%" font-family="Arial, sans-serif" font-size="20" fill="#00d4ff" text-anchor="middle" dominant-baseline="middle" font-weight="bold">{text}</text>
  </svg>"""
    encoded = urllib.parse.quote(svg)
    return "data:image/svg+xml;charset=utf-8," + encoded


def connect() -> sqlite3.Connection:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    return conn


def exec_script(conn: sqlite3.Connection, statements: List[str]) -> None:
    cur = conn.cursor()
    for stmt in statements:
        try:
            cur.execute(stmt)
        except sqlite3.OperationalError:
            # We intentionally ignore ALTER TABLE errors for existing columns.
            pass
    conn.commit()


def init_db(conn: sqlite3.Connection) -> None:
    conn.execute("PRAGMA foreign_keys = ON")

    # Tables
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          username TEXT UNIQUE NOT NULL,
          email TEXT UNIQUE NOT NULL,
          password TEXT NOT NULL,
          isAdmin INTEGER DEFAULT 0,
          createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS products (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL,
          description TEXT,
          image TEXT,
          date TEXT,
          price REAL DEFAULT 0,
          priceUsdt REAL DEFAULT 0,
          createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS orders (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          userId INTEGER NOT NULL,
          username TEXT NOT NULL,
          productId INTEGER NOT NULL,
          productName TEXT NOT NULL,
          quantity INTEGER DEFAULT 1,
          price REAL NOT NULL,
          totalAmount REAL NOT NULL,
          status TEXT DEFAULT 'pending',
          paymentMethod TEXT DEFAULT 'USDT',
          usdtWallet TEXT,
          network TEXT DEFAULT 'TRC20',
          txHash TEXT,
          createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
          paidAt DATETIME,
          completedAt DATETIME,
          FOREIGN KEY (userId) REFERENCES users(id),
          FOREIGN KEY (productId) REFERENCES products(id)
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS forum_posts (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          title TEXT NOT NULL,
          author TEXT NOT NULL,
          content TEXT NOT NULL,
          date TEXT,
          replies INTEGER DEFAULT 0,
          isPinned INTEGER DEFAULT 0,
          createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS forum_replies (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          postId INTEGER NOT NULL,
          author TEXT NOT NULL,
          content TEXT NOT NULL,
          parentReplyId INTEGER,
          createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (postId) REFERENCES forum_posts(id) ON DELETE CASCADE,
          FOREIGN KEY (parentReplyId) REFERENCES forum_replies(id) ON DELETE CASCADE
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS contact_messages (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL,
          email TEXT NOT NULL,
          message TEXT NOT NULL,
          read INTEGER DEFAULT 0,
          createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS payment_settings (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          wallet_address TEXT NOT NULL,
          network TEXT DEFAULT 'TRC20',
          autoDeleteMinutes INTEGER DEFAULT 30,
          updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    # Indexes and pragmas (best-effort)
    exec_script(
        conn,
        [
            "CREATE INDEX IF NOT EXISTS idx_users_username ON users(username)",
            "CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)",
            "CREATE INDEX IF NOT EXISTS idx_orders_userId ON orders(userId)",
            "CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status)",
            "CREATE INDEX IF NOT EXISTS idx_orders_productId ON orders(productId)",
            "CREATE INDEX IF NOT EXISTS idx_orders_createdAt ON orders(createdAt)",
            "CREATE INDEX IF NOT EXISTS idx_contact_messages_read ON contact_messages(read)",
            "CREATE INDEX IF NOT EXISTS idx_contact_messages_createdAt ON contact_messages(createdAt)",
            "CREATE INDEX IF NOT EXISTS idx_products_date ON products(date)",
            "CREATE INDEX IF NOT EXISTS idx_products_createdAt ON products(createdAt)",
            "CREATE INDEX IF NOT EXISTS idx_forum_posts_createdAt ON forum_posts(createdAt)",
            "CREATE INDEX IF NOT EXISTS idx_forum_posts_isPinned ON forum_posts(isPinned)",
            "CREATE INDEX IF NOT EXISTS idx_forum_replies_postId ON forum_replies(postId)",
            "CREATE INDEX IF NOT EXISTS idx_forum_replies_createdAt ON forum_replies(createdAt)",
            "PRAGMA journal_mode = WAL",
            "PRAGMA synchronous = NORMAL",
            "PRAGMA cache_size = -64000",
            "PRAGMA temp_store = MEMORY",
        ],
    )

    # Seed default data (best-effort, idempotent)
    cur = conn.cursor()

    cur.execute("SELECT id FROM users WHERE username = ?", ("admin",))
    if cur.fetchone() is None:
        cur.execute(
            "INSERT INTO users (username, email, password, isAdmin) VALUES (?, ?, ?, ?)",
            ("admin", "admin@yhthestudio.com", DEFAULT_ADMIN_BCRYPT_HASH, 1),
        )

    cur.execute("SELECT COUNT(*) AS count FROM products")
    if (cur.fetchone()["count"] or 0) == 0:
        products = [
            (
                "智能AI助手",
                "基于大语言模型的智能助手，提供24/7服务",
                generate_placeholder_svg("智能AI助手"),
                "2024-01-15",
                99.99,
                99.99,
            ),
            (
                "云端协作平台",
                "高效的团队协作工具，支持实时同步",
                generate_placeholder_svg("云端协作平台"),
                "2024-01-20",
                199.99,
                199.99,
            ),
            (
                "数据分析系统",
                "强大的数据分析和可视化平台",
                generate_placeholder_svg("数据分析系统"),
                "2024-02-01",
                299.99,
                299.99,
            ),
        ]
        cur.executemany(
            "INSERT INTO products (name, description, image, date, price, priceUsdt) VALUES (?, ?, ?, ?, ?, ?)",
            products,
        )

    cur.execute("SELECT COUNT(*) AS count FROM forum_posts")
    if (cur.fetchone()["count"] or 0) == 0:
        posts = [
            (
                "欢迎来到YHthestudio论坛",
                "Admin",
                "这里是技术交流的天地，欢迎大家分享经验和想法！",
                "2024-01-10",
                5,
            ),
            ("最新产品发布讨论", "TechLead", "关于我们最新AI产品的技术细节讨论", "2024-01-12", 12),
            ("前端开发最佳实践", "DevUser", "分享一些前端开发的经验和技巧", "2024-01-15", 8),
        ]
        cur.executemany(
            "INSERT INTO forum_posts (title, author, content, date, replies) VALUES (?, ?, ?, ?, ?)",
            posts,
        )

    cur.execute("SELECT COUNT(*) AS count FROM payment_settings")
    if (cur.fetchone()["count"] or 0) == 0:
        cur.execute(
            "INSERT INTO payment_settings (wallet_address, network, autoDeleteMinutes) VALUES (?, ?, ?)",
            ("TXYZabcdefghijklmnopqrstuvwxyz123456", "TRC20", 30),
        )

    conn.commit()


def row_to_dict(row: Optional[sqlite3.Row]) -> Optional[Dict[str, Any]]:
    if row is None:
        return None
    return {k: row[k] for k in row.keys()}


def rows_to_dicts(rows: List[sqlite3.Row]) -> List[Dict[str, Any]]:
    return [{k: r[k] for k in r.keys()} for r in rows]


class RpcRequest(BaseModel):
    op: str = Field(..., description="Operation name, e.g. users.findById")
    args: Dict[str, Any] = Field(default_factory=dict)


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup: initialize database
    conn = connect()
    try:
        init_db(conn)
    finally:
        conn.close()
    yield
    # Shutdown: cleanup if needed


app = FastAPI(title="YH_Web Python DB Backend", version="1.0.0", lifespan=lifespan)


@app.get("/health")
def health() -> Dict[str, Any]:
    return {"ok": True, "db_path": str(DB_PATH)}


@app.post("/rpc")
def rpc(req: RpcRequest) -> Dict[str, Any]:
    conn = connect()
    try:
        result = dispatch(conn, req.op, req.args)
        return {"ok": True, "result": result}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    finally:
        conn.close()


def dispatch(conn: sqlite3.Connection, op: str, args: Dict[str, Any]) -> Any:
    cur = conn.cursor()

    # Meta helpers (used by view-db.js replacement)
    if op == "meta.listTables":
        cur.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name ASC")
        return [r["name"] for r in cur.fetchall()]
    if op == "meta.tableData":
        table = str(args["table"])
        # basic allowlist-ish: only alnum + underscore
        if not table.replace("_", "").isalnum():
            raise ValueError("invalid table name")
        cur.execute(f"SELECT * FROM {table}")
        return rows_to_dicts(cur.fetchall())
    if op == "meta.tableCount":
        table = str(args["table"])
        if not table.replace("_", "").isalnum():
            raise ValueError("invalid table name")
        cur.execute(f"SELECT COUNT(*) AS count FROM {table}")
        row = cur.fetchone()
        return int(row["count"] if row else 0)

    # Users
    if op == "users.findAll":
        cur.execute("SELECT * FROM users ORDER BY createdAt DESC")
        return rows_to_dicts(cur.fetchall())
    if op == "users.findById":
        cur.execute("SELECT * FROM users WHERE id = ?", (args["id"],))
        return row_to_dict(cur.fetchone())
    if op == "users.findByUsername":
        cur.execute("SELECT * FROM users WHERE username = ?", (args["username"],))
        return row_to_dict(cur.fetchone())
    if op == "users.findByEmail":
        cur.execute("SELECT * FROM users WHERE email = ?", (args["email"],))
        return row_to_dict(cur.fetchone())
    if op == "users.create":
        cur.execute(
            "INSERT INTO users (username, email, password, isAdmin) VALUES (?, ?, ?, ?)",
            (
                args["username"],
                args["email"],
                args["password"],
                int(args.get("isAdmin", 0)),
            ),
        )
        conn.commit()
        return int(cur.lastrowid)
    if op == "users.update":
        if args.get("password"):
            cur.execute(
                "UPDATE users SET email = ?, password = ?, isAdmin = ? WHERE id = ?",
                (args["email"], args["password"], int(args["isAdmin"]), args["id"]),
            )
        else:
            cur.execute(
                "UPDATE users SET email = ?, isAdmin = ? WHERE id = ?",
                (args["email"], int(args["isAdmin"]), args["id"]),
            )
        conn.commit()
        return None
    if op == "users.delete":
        cur.execute("DELETE FROM users WHERE id = ? AND isAdmin = 0", (args["id"],))
        conn.commit()
        return None

    # Products
    if op == "products.findAll":
        cur.execute("SELECT * FROM products ORDER BY date DESC, id DESC")
        return rows_to_dicts(cur.fetchall())
    if op == "products.findById":
        cur.execute("SELECT * FROM products WHERE id = ?", (args["id"],))
        return row_to_dict(cur.fetchone())
    if op == "products.create":
        cur.execute(
            "INSERT INTO products (name, description, image, date, price, priceUsdt) VALUES (?, ?, ?, ?, ?, ?)",
            (
                args["name"],
                args.get("description"),
                args.get("image"),
                args.get("date"),
                args.get("price", 0),
                args.get("priceUsdt", 0),
            ),
        )
        conn.commit()
        return int(cur.lastrowid)
    if op == "products.update":
        cur.execute(
            "UPDATE products SET name = ?, description = ?, image = ?, date = ?, price = ?, priceUsdt = ? WHERE id = ?",
            (
                args["name"],
                args.get("description"),
                args.get("image"),
                args.get("date"),
                args.get("price", 0),
                args.get("priceUsdt", 0),
                args["id"],
            ),
        )
        conn.commit()
        return None
    if op == "products.delete":
        cur.execute("DELETE FROM products WHERE id = ?", (args["id"],))
        conn.commit()
        return None

    # Orders
    if op == "orders.findAll":
        status_filter = str(args.get("statusFilter", "") or "").strip()
        if status_filter:
            cur.execute(
                "SELECT * FROM orders WHERE status = ? ORDER BY createdAt DESC",
                (status_filter,),
            )
        else:
            cur.execute("SELECT * FROM orders ORDER BY createdAt DESC")
        return rows_to_dicts(cur.fetchall())
    if op == "orders.findById":
        cur.execute("SELECT * FROM orders WHERE id = ?", (args["id"],))
        return row_to_dict(cur.fetchone())
    if op == "orders.findByUserId":
        cur.execute(
            "SELECT * FROM orders WHERE userId = ? ORDER BY createdAt DESC",
            (args["userId"],),
        )
        return rows_to_dicts(cur.fetchall())
    if op == "orders.create":
        order = args["orderData"]
        created_at = now_iso()
        cur.execute(
            """
            INSERT INTO orders (
              userId, username, productId, productName, quantity, price, totalAmount,
              status, paymentMethod, usdtWallet, network, createdAt
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                order["userId"],
                order["username"],
                order["productId"],
                order["productName"],
                order.get("quantity", 1),
                order["price"],
                order["totalAmount"],
                order.get("status", "pending"),
                order.get("paymentMethod", "USDT"),
                order.get("usdtWallet"),
                order.get("network", "TRC20"),
                created_at,
            ),
        )
        conn.commit()
        return int(cur.lastrowid)
    if op == "orders.updateStatus":
        status = args["status"]
        order_id = args["id"]
        paid_at = now_iso() if status == "paid" else None
        completed_at = now_iso() if status == "completed" else None

        sql = "UPDATE orders SET status = ?"
        params: List[Any] = [status]
        if paid_at is not None:
            sql += ", paidAt = ?"
            params.append(paid_at)
        if completed_at is not None:
            sql += ", completedAt = ?"
            params.append(completed_at)
        sql += " WHERE id = ?"
        params.append(order_id)
        cur.execute(sql, params)
        conn.commit()
        return None
    if op == "orders.updateTxHash":
        cur.execute(
            "UPDATE orders SET txHash = ?, paidAt = ? WHERE id = ?",
            (args["txHash"], now_iso(), args["id"]),
        )
        conn.commit()
        return None
    if op == "orders.getStats":
        cur.execute("SELECT COUNT(*) AS total FROM orders")
        total = int(cur.fetchone()["total"])
        cur.execute("SELECT COUNT(*) AS pending FROM orders WHERE status = 'pending'")
        pending = int(cur.fetchone()["pending"])
        cur.execute(
            "SELECT COALESCE(SUM(totalAmount), 0) AS revenue FROM orders WHERE status IN ('paid','completed')"
        )
        revenue = cur.fetchone()["revenue"] or 0
        return {"total": total, "pending": pending, "revenue": revenue}
    if op == "orders.delete":
        cur.execute("DELETE FROM orders WHERE id = ?", (args["id"],))
        conn.commit()
        return None
    if op == "orders.deleteExpiredPending":
        minutes = int(args["minutes"])
        cur.execute(
            """
            DELETE FROM orders
            WHERE status = 'pending'
            AND datetime(replace(replace(createdAt,'T',' '),'Z',''), '+' || ? || ' minutes') < datetime('now')
            """,
            (minutes,),
        )
        conn.commit()
        return int(cur.rowcount if cur.rowcount is not None else 0)

    # Forum posts
    if op == "forumPosts.findAll":
        cur.execute("SELECT * FROM forum_posts ORDER BY isPinned DESC, date DESC, id DESC")
        return rows_to_dicts(cur.fetchall())
    if op == "forumPosts.findById":
        cur.execute("SELECT * FROM forum_posts WHERE id = ?", (args["id"],))
        return row_to_dict(cur.fetchone())
    if op == "forumPosts.create":
        cur.execute(
            "INSERT INTO forum_posts (title, author, content, date, replies, isPinned) VALUES (?, ?, ?, ?, ?, 0)",
            (args["title"], args["author"], args["content"], args.get("date"), int(args.get("replies", 0))),
        )
        conn.commit()
        return int(cur.lastrowid)
    if op == "forumPosts.update":
        cur.execute(
            "UPDATE forum_posts SET title = ?, author = ?, content = ?, date = ?, replies = ? WHERE id = ?",
            (
                args["title"],
                args["author"],
                args["content"],
                args.get("date"),
                int(args.get("replies", 0)),
                args["id"],
            ),
        )
        conn.commit()
        return None
    if op == "forumPosts.togglePin":
        cur.execute("SELECT isPinned FROM forum_posts WHERE id = ?", (args["id"],))
        row = cur.fetchone()
        if row is None:
            raise ValueError("帖子不存在")
        new_status = 0 if int(row["isPinned"] or 0) == 1 else 1
        cur.execute("UPDATE forum_posts SET isPinned = ? WHERE id = ?", (new_status, args["id"]))
        conn.commit()
        return int(new_status)
    if op == "forumPosts.delete":
        cur.execute("DELETE FROM forum_posts WHERE id = ?", (args["id"],))
        conn.commit()
        return None
    if op == "forumPosts.incrementReplies":
        cur.execute("UPDATE forum_posts SET replies = replies + 1 WHERE id = ?", (args["id"],))
        conn.commit()
        return None

    # Forum replies
    if op == "forumReplies.findByPostId":
        cur.execute(
            "SELECT * FROM forum_replies WHERE postId = ? ORDER BY createdAt ASC",
            (args["postId"],),
        )
        return rows_to_dicts(cur.fetchall())
    if op == "forumReplies.findById":
        cur.execute("SELECT * FROM forum_replies WHERE id = ?", (args["id"],))
        return row_to_dict(cur.fetchone())
    if op == "forumReplies.create":
        with conn:
            cur.execute(
                "INSERT INTO forum_replies (postId, author, content, parentReplyId) VALUES (?, ?, ?, ?)",
                (
                    args["postId"],
                    args["author"],
                    args["content"],
                    args.get("parentReplyId"),
                ),
            )
            reply_id = int(cur.lastrowid)
            cur.execute("UPDATE forum_posts SET replies = replies + 1 WHERE id = ?", (args["postId"],))
        return reply_id
    if op == "forumReplies.delete":
        cur.execute("DELETE FROM forum_replies WHERE id = ?", (args["id"],))
        conn.commit()
        return None

    # Payment settings
    if op == "paymentSettings.get":
        cur.execute("SELECT * FROM payment_settings ORDER BY id DESC LIMIT 1")
        return row_to_dict(cur.fetchone())
    if op == "paymentSettings.update":
        wallet = args["walletAddress"]
        network = args.get("network", "TRC20")
        minutes = int(args.get("autoDeleteMinutes", 30))
        updated = now_iso()
        cur.execute("SELECT COUNT(*) AS count FROM payment_settings")
        cnt = int(cur.fetchone()["count"])
        if cnt == 0:
            cur.execute(
                "INSERT INTO payment_settings (wallet_address, network, autoDeleteMinutes, updatedAt) VALUES (?, ?, ?, ?)",
                (wallet, network, minutes, updated),
            )
            conn.commit()
            return int(cur.lastrowid)
        cur.execute(
            """
            UPDATE payment_settings
            SET wallet_address = ?, network = ?, autoDeleteMinutes = ?, updatedAt = ?
            WHERE id = (SELECT id FROM payment_settings ORDER BY id DESC LIMIT 1)
            """,
            (wallet, network, minutes, updated),
        )
        conn.commit()
        return None

    raise ValueError(f"Unknown op: {op}")

